### ISSUE TITLE
Build failure with GHC 9.4

### ISSUE THREAD

**Issue by andreasabel** [haskell-hvr/brotli#5]
`brotli-0.0.0.0` fails to compile with GHC 9.4:
```
[2 of 2] Compiling Codec.Compression.Brotli ( src/Codec/Compression/Brotli.hs, dist/build/Codec/Compression/Brotli.o, dist/build/Codec/Compression/Brotli.dyn_o )

src/Codec/Compression/Brotli.hs:270:13: error:
    • Could not deduce (MonadFail (ST s2))
        arising from a do statement
        with the failable pattern ‘(rc, 0)’
```
This is:
- https://github.com/haskell/core-libraries-committee/issues/33
