### PR TITLE
brotli 0.0.0.1: use internalError instead of MonadFail ST (GHC 9.4)

### LINKED ISSUE #5: Build failure with GHC 9.4
`brotli-0.0.0.0` fails to compile with GHC 9.4:
```
[2 of 2] Compiling Codec.Compression.Brotli ( src/Codec/Compression/Brotli.hs, dist/build/Codec/Compression/Brotli.o, dist/build/Codec/Compression/Brotli.dyn_o )

src/Codec/Compression/Brotli.hs:270:13: error:
    • Could not deduce (MonadFail (ST s2))
        arising from a do statement
        with the failable pattern ‘(rc, 0)’
```
This is:
- https://github.com/haskell/core-libraries-committee/issues/33

### PR DESCRIPTION
**Pull request by andreasabel**
- fixes #5
- bump `base` and `transformers`
- include GHC 9.4 in Haskell CI
- add `-Wcompat`

### CODE REVIEW

**Comment by andreasabel** [comment]
Cannot upload candidate, missing upload rights: https://hackage.haskell.org/package/brotli/maintainers/

**Comment by andreasabel** [comment]
Published: https://hackage.haskell.org/package/brotli-0.0.0.1
